"""empty message

Revision ID: 1b1b014520ca
Revises: 0956e6fc84c6
Create Date: 2020-07-21 00:04:02.216626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1b014520ca'
down_revision = '0956e6fc84c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mg_state', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mg_state')
    # ### end Alembic commands ###
